services:

  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Config: '@=service("OxidSolutionCatalysts\\PayPal\\Core\\Registry").getConfig()'
      OxidEsales\Eshop\Core\Session: '@=service("OxidSolutionCatalysts\\PayPal\\Core\\Registry").getSession()'
      OxidEsales\Eshop\Core\Language: '@=service("OxidSolutionCatalysts\\PayPal\\Core\\Registry").getLang()'
      OxidEsales\Eshop\Core\UtilsDate: '@=service("OxidSolutionCatalysts\\PayPal\\Core\\Registry").getUtilsDate()'
      OxidEsales\Eshop\Core\Request: '@=service("OxidSolutionCatalysts\\PayPal\\Core\\Registry").getRequest()'

  OxidSolutionCatalysts\PayPal\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true

  OxidSolutionCatalysts\PayPal\Logger:
    class: Monolog\Logger
    factory: ['@OxidSolutionCatalysts\PayPal\Logger\Factory', 'create']
    public: true

  OxidSolutionCatalysts\PayPal\Logger\Factory:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Factory\MonologLoggerFactory
    public: true
    arguments:
      $configuration: '@OxidSolutionCatalysts\PayPal\Logger\Configuration'

  OxidSolutionCatalysts\PayPal\Logger\Configuration:
    class: OxidEsales\EshopCommunity\Internal\Framework\Logger\Configuration\MonologConfiguration
    public: true
    arguments:
      $loggerName: 'PayPal Payment Logger'
      $logFilePath: '@=service("OxidSolutionCatalysts\\PayPal\\Service\\Context").getPayPalLogFilePath()'
      $logLevel: !php/const Psr\Log\LogLevel::INFO

  OxidSolutionCatalysts\PayPal\Service\:
    resource: 'src/Service/*'
    public: true

  OxidSolutionCatalysts\PayPal\Service\Payment:
    class: OxidSolutionCatalysts\PayPal\Service\Payment
    public: true
    arguments:
      Psr\Log\LoggerInterface: '@OxidSolutionCatalysts\PayPal\Logger'

  OxidSolutionCatalysts\PayPal\Service\ModuleSettings:
    class: OxidSolutionCatalysts\PayPal\Service\ModuleSettings
    public: true
    arguments:
      Psr\Log\LoggerInterface: '@OxidSolutionCatalysts\PayPal\Logger'

  OxidSolutionCatalysts\PayPal\Service\SCAValidatorInterface:
    class:  OxidSolutionCatalysts\PayPal\Service\SCAValidator
    public: true
