name: Update tag

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  repository_dispatch:
    types: [push-tag]

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: ([v](([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)
          replace: ${{ github.event.client_payload.tag }}
          include: .github/workflows/main.yml

      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update tag to ${{ github.event.client_payload.tag }}"